//--------------------------------------------------------------------------------------------
//
// Generated by X-HDL VHDL Translator - Version 2.0.0 Feb. 1, 2011
// ?? ?? 10 2026 09:22:40
//
//      Input file      : 
//      Component name  : fadd
//      Author          : 
//      Company         : 
//
//      Description     : 
//
//
//--------------------------------------------------------------------------------------------


module fadd(IN_A, IN_B, Cin, SUM, CARRY);
   input   IN_A;
   input   IN_B;
   input   Cin;
   output  SUM;
   output  CARRY;
   
   
   assign SUM = IN_A ^ IN_B ^ Cin;
   assign CARRY = (IN_A & IN_B) | (Cin & (IN_A ^ IN_B));
   
endmodule
