----------------------------------------------------------------------------------------------
--
-- Generated by X-HDL Verilog Translator - Version 2.0.0 Feb. 1, 2011
-- ?? ?? 10 2026 09:25:17
--
--      Input file      : 
--      Component name  : Tb_Fadd4
--      Author          : 
--      Company         : 
--
--      Description     : 
--
--
----------------------------------------------------------------------------------------------

LIBRARY ieee;
   USE ieee.std_logic_1164.all;
   USE ieee.std_logic_unsigned.all;

ENTITY Tb_Fadd4 IS
END Tb_Fadd4;

ARCHITECTURE trans OF Tb_Fadd4 IS
   
   SIGNAL IN_A : STD_LOGIC_VECTOR(3 DOWNTO 0);
   SIGNAL IN_B : STD_LOGIC_VECTOR(3 DOWNTO 0);
   SIGNAL SUM  : STD_LOGIC_VECTOR(3 DOWNTO 0);
   SIGNAL Cout : STD_LOGIC;
BEGIN
   
   
   
   DUT : Fadd4
      PORT MAP (
         in_a  => IN_A,
         in_b  => IN_B,
         sum   => SUM,
         cout  => Cout
      );
   
   PROCESS 
   BEGIN
      IN_A <= "0111";
      IN_B <= "1000";
      WAIT FOR 500 ns;
      -- $finish();
      WAIT;
   END PROCESS;
   
   
   PROCESS (50)
   BEGIN
      IN_A <= IN_A + "0001";
   END PROCESS;
   
   PROCESS (50)
   BEGIN
      IN_B <= IN_B + "0001";
   END PROCESS;
   
   
   PROCESS (50)
   BEGIN
      WAIT FOR 1 ns;
      -- $monitor("Time:%0t | IN_A=%d + IN_B=%d = SUM=%d (Cout=%b)", NOW, IN_A, IN_B, SUM, Cout);
   END PROCESS;
   
   
END trans;


